# Generated by Django 4.0.5 on 2022-06-23 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0005_profile_country_profile_date_of_birth_profile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('non-binary', 'non-binary'), ('male', 'male'), ('female', 'female')], default='non-binary', max_length=30, null=True),
        ),
    ]
