# Generated by Django 4.0.5 on 2022-06-24 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0010_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='account',
        ),
    ]
